Added enable-jfr flag to configure
AdoptOpenJDK/openjdk8-upstream-binaries pull request #4
Opened 2020-03-15 10:33 UTC by jhuttana

2020-03-15 19:08 UTC, karianna commented
@jerboaa Not sure this is the place you want to have this patch?

2020-03-23 15:12 UTC, jerboaa requested changes
@jhuttana Thanks for the PR! Please make similar changes to the build script when BRs are already installed: File `build-openjdk8.sh`.

2020-03-23 15:12 UTC, jerboaa commented on install-rhel6-deps-build-openjdk8.sh
> +CLONE_URL=https://hg.openjdk.java.net/jdk8u/jdk8u-dev
We don't want to change the clone URL. We'll only merge this PR once the feature has been merged into jdk8u. So please revert this hunk.

2020-03-23 15:13 UTC, jerboaa commented
> @jerboaa Not sure this is the place you want to have this patch?

@karianna It's the right place. We want to build an additional artifact for 8u262 with JFR enabled while it's still disabled for default config.

2020-03-24 19:39 UTC, jerboaa requested changes

2020-03-24 19:39 UTC, jerboaa commented on build-openjdk8.sh
> +    if [ "\$debug" == "release-jfr" ]; then
In this script no escaping, please. Should be `$debug` not `\$debug`.

2020-03-24 19:39 UTC, jerboaa commented on build-openjdk8.sh
> +       dbg_level="\$debug"
Same.

2020-03-24 19:39 UTC, jerboaa commented on build-openjdk8.sh
> +       --with-debug-level="\$dbg_level" \
Same.

2020-03-25 12:16 UTC, jerboaa commented
@jhuttana So I took this for a spin and there are a couple of thoughts. The build output looks similar to this post patch:

```
$ find build/ -name \*.tar.gz
build/release/images/OpenJDK8U-jdk_x64_linux_8u262b00_ea-debuginfo.tar.gz
build/release/images/OpenJDK8U-jre_x64_linux_8u262b00_ea.tar.gz
build/release/images/OpenJDK8U-jre_x64_linux_8u262b00_ea-debuginfo.tar.gz
build/release/images/OpenJDK8U-jdk_x64_linux_8u262b00_ea.tar.gz
build/OpenJDK8U-sources_8u262b00_ea.tar.gz
build/slowdebug/images/OpenJDK8U-jdk_x64_linux_8u262b00_ea-slowdebug.tar.gz
build/slowdebug/images/OpenJDK8U-jdk_x64_linux_8u262b00_ea-slowdebug-debuginfo.tar.gz
build/release-jfr/images/OpenJDK8U-jdk_x64_linux_8u262b00_ea-debuginfo.tar.gz
build/release-jfr/images/OpenJDK8U-jdk_x64_linux_8u262b00_ea.tar.gz
```

However, we need to change the filename for the JFR-enabled artefacts. They're now named the same as the regular tarballs, namely `OpenJDK8U-jdk_x64_linux_8u262b00_ea.tar.gz`. The JFR artefact should be called `OpenJDK8U-jdk-jfr_x64_linux_8u262b00_ea.tar.gz`. Also, we should try to get JRE's packaged up for the JFR artefacts too: `OpenJDK8U-jre-jfr_x64_linux_8u262b00_ea.tar.gz`

2020-04-06 14:55 UTC, jerboaa requested changes
@jhuttana Please move the config of filenames to the top of the script so we have them in one place when we need to change them.

2020-04-06 14:55 UTC, jerboaa commented on build-openjdk8.sh
> +      TARBALL_NAME="${TARBALL_BASE_NAME}-jdk-jfr_${PLATFORM_VERSION}"
I'd prefer if we kept global config variables at the top of the script. So the suggestion would be to define `TARBALL_NAME_JFR` and `TARBALL_NAME_JFR_JRE` and use them in a local variable, say `archive_name` in the script like:

```
archive_name="$TARBALL_NAME"
jre_archive_name="$TARBALL_NAME_JRE"
if [ "${debug}_" == "release-jfr_" ]; then
  archive_name="$TARBALL_NAME_JFR"
  jre_archive_name="$TARBALL_NAME_JFR_JRE"
fi
```

2020-04-07 15:18 UTC, jerboaa approved these changes
LGTM. We'll merge this once the 8u262 EA builds cycle starts.

2020-04-28 11:00 UTC, jerboaa commented
jdk8u262-b01 got tagged. Merging this now.

2020-04-28 11:00 UTC, merged